apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rollout-demo
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/app-root: /
spec:
  rules:
  - host: rollout-demo.dev.argoproj.io
    http:
      paths:
      - path: /
        backend:
          serviceName: rollout-demo
          servicePort: 80
